apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  labels:
    team: devops_change_base_deployment_file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hw-deployment
  template:
    metadata:
      labels:
        app: hw-deployment
    spec:
      containers:
      - name: app
        image: gcr.io/google-samples/node-hello:1.0
        # this image is from google.
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP


# test comment
