apiVersion: v1
kind: Service
metadata:
  name: hw-service
spec:
  type: ClusterIP
  #note that this is not an exposed port but internal port.
  ports:
  - name: http
    port: 8080
  selector:
    app: hw-deployment
