apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
# this time the deployment will concern diffs in the deployment and service files.

