apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-svc
  namespace: {{ .Namespace }}
  {{ if eq .Params.METRICS_ENABLED "true" }}
  labels:
    "kudo.dev/servicemonitor": "true"
  {{ end }}
spec:
  ports:
    - port: {{ .Params.BROKER_PORT }}
      name: server
    {{ if eq .Params.TRANSPORT_ENCRYPTION_ENABLED "true" }}
    - port: {{ .Params.BROKER_PORT_TLS }}
      name: server-tls
    {{ end }}
    - port: {{ .Params.CLIENT_PORT }}
      name: client
    {{ if eq .Params.METRICS_ENABLED "true" }}
    - port: {{ .Params.METRICS_PORT }}
      name: metrics
    - port: {{ .Params.KAFKA_NODE_EXPORTER_PORT }}
      name: ne-metrics
    {{ end }}
  clusterIP: None
  selector:
    app: kafka
    kudo.dev/instance: {{ .Name }}