apiVersion: kudo.dev/v1beta1
parameters:
  - name: masters
    description: "Number of Redis masters"
    default: "3"
    displayName: "Redis masters"
  - name: client_port
    description: "Client port"
    default: "6379"
  - name: gossip_port
    description: "Gossip port"
    default: "16379"