apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Name }}-pdb
  namespace: {{ .Namespace }}
  labels:
    app: zookeeper
    zookeeper: {{ .Name }}
spec:
  selector:
    matchLabels:
      app: zookeeper
      kudo.dev/instance: {{ .Name }}
  maxUnavailable: 1
