apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-hs
  namespace: {{ .Namespace }}
  labels:
    app: zookeeper
    zookeeper: {{ .Name }}
spec:
  ports:
    - port: {{ .Params.SERVER_PORT }}
      name: server
    - port: {{ .Params.ELECTION_PORT }}
      name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
    instance: {{ .Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Name }}-cs
  namespace: {{ .Namespace }}
  labels:
    app: zookeeper
    zookeeper: {{ .Name }}
spec:
  ports:
    - port: {{ .Params.CLIENT_PORT }}
      name: client
  selector:
    app: zookeeper
    instance: {{ .Name }}