apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
# needs this as a relative base to which to compare tehe changes.
# note that this is 2 directory structures up.
patchesStrategicMerge:
- deployment.yaml
# more files can be added here as required.
